# Travis.ci build file
language: python
python:
    - 2.7

# command to install software and tests prerequistes
install:
    pip install WebTest
    python setup.py install

# command to run tests
script: nosetests
