# Travis.ci build file
language: python
python:
    - 2.7

# command to install software
install:
    python setup.py install

# command to install tests prerequistes
after_install:
    pip install WebTest

# command to run tests
script: nosetests
