# Travis.ci build file
language: python
python:
    - 2.7

# command to install software and tests prerequistes
install:
    - python setup.py develop
    - pip install coverage webtest --use-mirrors

# command to run tests
script:
    - nosetests
